version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pointsdb
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  py-server:
    build: ./py_server
    ports:
      - "5002:5002"
    depends_on:
      - mysql

  py-client:
    build: ./py_client
    depends_on:
      - py-server

  c-server:
    build: ./c_server
    ports:
      - "5003:5003"
    depends_on:
      - mysql

c-client:
    build: ./c_client
    depends_on:
      - c-server

