services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pointsdb
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

    py-server:
    build: ./py_server
    container_name: py-server
    ports:
      - "5002:5002"
    depends_on:
      - mysql
    networks:
      - itt440

  py-client:
    build: ./py_client
    container_name: py-client
    depends_on:
      - py-server
    networks:
      - itt440

networks:
  itt440:
